CREATE TABLE IF NOT EXISTS company_details (
  security_id INT PRIMARY KEY,
  symbol VARCHAR(50) NOT NULL,
  company_name VARCHAR(255),
  sector_name VARCHAR(100),
  instrument_type VARCHAR(50),
  issue_manager VARCHAR(255),
  share_registrar VARCHAR(255),
  listing_date VARCHAR(20),
  total_listed_shares DECIMAL(20, 2),
  paid_up_capital DECIMAL(20, 2),
  total_paid_up_value DECIMAL(20, 2),
  email VARCHAR(255),
  website VARCHAR(255),
  status VARCHAR(50),
  permitted_to_trade VARCHAR(50),
  promoter_shares DECIMAL(20, 2),
  public_shares DECIMAL(20, 2),
  market_capitalization DECIMAL(25, 2),
  logo_url VARCHAR(500),
  is_logo_placeholder TINYINT(1) DEFAULT 1,
  last_traded_price DECIMAL(15, 2),
  open_price DECIMAL(15, 2),
  close_price DECIMAL(15, 2),
  high_price DECIMAL(15, 2),
  low_price DECIMAL(15, 2),
  previous_close DECIMAL(15, 2),
  fifty_two_week_high DECIMAL(15, 2),
  fifty_two_week_low DECIMAL(15, 2),
  total_traded_quantity BIGINT,
  total_trades INT,
  average_traded_price DECIMAL(15, 2),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_company_details_symbol (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
