CREATE TABLE IF NOT EXISTS notification_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  fcm_token VARCHAR(255) UNIQUE NOT NULL,
  device_type VARCHAR(50),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
