-- Update transactions.type column comment to include MERGER_OUT and MERGER_IN

ALTER TABLE transactions 
  MODIFY COLUMN type VARCHAR(50) NOT NULL 
  COMMENT 'IPO, FPO, AUCTION, RIGHTS, SECONDARY_BUY, SECONDARY_SELL, BONUS, DIVIDEND, MERGER_OUT, MERGER_IN';
