CREATE TABLE IF NOT EXISTS merger_acquisitions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  merger_acquisition_id INT UNIQUE,
  sector_id INT,
  sector_name VARCHAR(100),
  nepali_sector_name VARCHAR(100),
  new_company_name VARCHAR(255),
  nepali_new_company_name VARCHAR(255),
  new_company_stock_symbol VARCHAR(20),
  companies JSON,
  swap_ratio VARCHAR(100),
  mou_date_ad DATE,
  mou_date_bs VARCHAR(20),
  final_approval_date_ad DATE,
  final_approval_date_bs VARCHAR(20),
  joint_date_ad DATE,
  joint_date_bs VARCHAR(20),
  action VARCHAR(50),
  is_completed BOOLEAN DEFAULT FALSE,
  is_trading BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_merger_symbol_status (new_company_stock_symbol, is_completed),
  INDEX idx_merger_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
